# Form implementation generated from reading ui file 'scalpel.ui'
#
# Created by: PyQt6 UI code generator 6.1.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt6 import QtCore, QtGui, QtWidgets
from pathlib import Path
from datetime import datetime
from dateutil.tz import tzlocal
from dateutil import parser as dt_parser
from ruamel.yaml import YAML

server_basepath = Path("X:/")


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.setEnabled(True)
        Form.resize(1321, 769)
        font = QtGui.QFont()
        font.setPointSize(11)
        Form.setFont(font)
        Form.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.ArrowCursor))
        Form.setWindowOpacity(1.0)
        Form.setToolTip("")
        Form.setStyleSheet("QPushButton{\n"
"\n"
"    background-color: rgb(170, 255, 255);\n"
"    \n"
"    border-color: rgb(0, 0, 0);\n"
"\n"
"    color: rgb(0, 0, 0);\n"
"\n"
"}")
        self.save_metadata_btn = QtWidgets.QPushButton(Form)
        self.save_metadata_btn.setGeometry(QtCore.QRect(1180, 670, 131, 81))
        self.save_metadata_btn.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.save_metadata_btn.setStyleSheet("QPushButton{\n"
"\n"
"    background-color: rgb(170, 255, 255);\n"
"    \n"
"    border-color: rgb(0, 0, 0);\n"
"\n"
"    color: rgb(0, 0, 0);\n"
"\n"
"}")
        self.save_metadata_btn.setShortcut("")
        self.save_metadata_btn.setDefault(False)
        self.save_metadata_btn.setFlat(False)
        self.save_metadata_btn.setObjectName("save_metadata_btn")
        self.start_time = QtWidgets.QTimeEdit(Form)
        self.start_time.setGeometry(QtCore.QRect(1160, 500, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.start_time.setFont(font)
        self.start_time.setStyleSheet("QTimeEdit {\n"
"\n"
"background-color: \"white\"\n"
"\n"
"}")
        self.start_time.setObjectName("start_time")
        self.finish_time = QtWidgets.QTimeEdit(Form)
        self.finish_time.setGeometry(QtCore.QRect(1160, 540, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.finish_time.setFont(font)
        self.finish_time.setStyleSheet("QTimeEdit {\n"
"\n"
"background-color: \"white\"\n"
"\n"
"}")
        self.finish_time.setObjectName("finish_time")
        self.surgeon = QtWidgets.QPlainTextEdit(Form)
        self.surgeon.setGeometry(QtCore.QRect(370, 10, 111, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.surgeon.setFont(font)
        self.surgeon.setStyleSheet("QPlainTextEdit {\n"
"\n"
"background-color: \"white\"\n"
"\n"
"}")
        self.surgeon.setTextInteractionFlags(QtCore.Qt.TextInteractionFlag.NoTextInteraction)
        self.surgeon.setObjectName("surgeon")
        self.start = QtWidgets.QPlainTextEdit(Form)
        self.start.setGeometry(QtCore.QRect(1050, 500, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.start.setFont(font)
        self.start.setStyleSheet("QPlainTextEdit {\n"
"\n"
"background-color: \"white\"\n"
"\n"
"}")
        self.start.setTextInteractionFlags(QtCore.Qt.TextInteractionFlag.NoTextInteraction)
        self.start.setObjectName("start")
        self.surgeon_val = QtWidgets.QLineEdit(Form)
        self.surgeon_val.setGeometry(QtCore.QRect(480, 10, 131, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.surgeon_val.setFont(font)
        self.surgeon_val.setStyleSheet("QLineEdit {\n"
"\n"
"background-color: \"white\"\n"
"\n"
"}")
        self.surgeon_val.setInputMask("")
        self.surgeon_val.setText("")
        self.surgeon_val.setObjectName("surgeon_val")
        self.finish = QtWidgets.QPlainTextEdit(Form)
        self.finish.setGeometry(QtCore.QRect(1050, 540, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.finish.setFont(font)
        self.finish.setStyleSheet("QPlainTextEdit {\n"
"\n"
"background-color: \"white\"\n"
"\n"
"}")
        self.finish.setTextInteractionFlags(QtCore.Qt.TextInteractionFlag.NoTextInteraction)
        self.finish.setObjectName("finish")
        self.stereotax_val = QtWidgets.QLineEdit(Form)
        self.stereotax_val.setGeometry(QtCore.QRect(480, 40, 131, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.stereotax_val.setFont(font)
        self.stereotax_val.setStyleSheet("QLineEdit {\n"
"\n"
"background-color: \"white\"\n"
"\n"
"}")
        self.stereotax_val.setInputMask("")
        self.stereotax_val.setText("")
        self.stereotax_val.setObjectName("stereotax_val")
        self.stereotax = QtWidgets.QPlainTextEdit(Form)
        self.stereotax.setGeometry(QtCore.QRect(370, 40, 111, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.stereotax.setFont(font)
        self.stereotax.setStyleSheet("QPlainTextEdit {\n"
"\n"
"background-color: \"white\"\n"
"\n"
"}")
        self.stereotax.setTextInteractionFlags(QtCore.Qt.TextInteractionFlag.NoTextInteraction)
        self.stereotax.setObjectName("stereotax")
        self.lambda_val = QtWidgets.QLineEdit(Form)
        self.lambda_val.setGeometry(QtCore.QRect(120, 250, 131, 31))
        self.lambda_val.setStyleSheet("QLineEdit {\n"
"\n"
"background-color: \"white\"\n"
"\n"
"}")
        self.lambda_val.setInputMask("")
        self.lambda_val.setText("")
        self.lambda_val.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lambda_val.setObjectName("lambda_val")
        self.bregma_val = QtWidgets.QLineEdit(Form)
        self.bregma_val.setGeometry(QtCore.QRect(120, 210, 131, 31))
        self.bregma_val.setStyleSheet("QLineEdit {\n"
"\n"
"background-color: \"white\"\n"
"\n"
"}")
        self.bregma_val.setInputMask("")
        self.bregma_val.setText("")
        self.bregma_val.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.bregma_val.setObjectName("bregma_val")
        self.bregma = QtWidgets.QPlainTextEdit(Form)
        self.bregma.setGeometry(QtCore.QRect(10, 210, 111, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.bregma.setFont(font)
        self.bregma.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.bregma.setStyleSheet("QPlainTextEdit {\n"
"\n"
"background-color: \"white\"\n"
"\n"
"}")
        self.bregma.setTabChangesFocus(True)
        self.bregma.setTextInteractionFlags(QtCore.Qt.TextInteractionFlag.NoTextInteraction)
        self.bregma.setObjectName("bregma")
        self.lmbda = QtWidgets.QPlainTextEdit(Form)
        self.lmbda.setGeometry(QtCore.QRect(10, 250, 111, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.lmbda.setFont(font)
        self.lmbda.setStyleSheet("QPlainTextEdit {\n"
"\n"
"background-color: \"white\"\n"
"\n"
"}")
        self.lmbda.setTextInteractionFlags(QtCore.Qt.TextInteractionFlag.NoTextInteraction)
        self.lmbda.setObjectName("lmbda")
        self.level_right = QtWidgets.QPlainTextEdit(Form)
        self.level_right.setGeometry(QtCore.QRect(10, 330, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.level_right.setFont(font)
        self.level_right.setStyleSheet("QPlainTextEdit {\n"
"\n"
"background-color: \"white\"\n"
"\n"
"}")
        self.level_right.setTextInteractionFlags(QtCore.Qt.TextInteractionFlag.NoTextInteraction)
        self.level_right.setObjectName("level_right")
        self.level_right_val = QtWidgets.QLineEdit(Form)
        self.level_right_val.setGeometry(QtCore.QRect(120, 330, 131, 31))
        self.level_right_val.setStyleSheet("QLineEdit {\n"
"\n"
"background-color: \"white\"\n"
"\n"
"}")
        self.level_right_val.setInputMask("")
        self.level_right_val.setText("")
        self.level_right_val.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.level_right_val.setObjectName("level_right_val")
        self.level_left = QtWidgets.QPlainTextEdit(Form)
        self.level_left.setGeometry(QtCore.QRect(10, 290, 111, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.level_left.setFont(font)
        self.level_left.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.level_left.setStyleSheet("QPlainTextEdit {\n"
"\n"
"background-color: \"white\"\n"
"\n"
"}")
        self.level_left.setTabChangesFocus(True)
        self.level_left.setTextInteractionFlags(QtCore.Qt.TextInteractionFlag.NoTextInteraction)
        self.level_left.setObjectName("level_left")
        self.level_left_val = QtWidgets.QLineEdit(Form)
        self.level_left_val.setGeometry(QtCore.QRect(120, 290, 131, 31))
        self.level_left_val.setStyleSheet("QLineEdit {\n"
"\n"
"background-color: \"white\"\n"
"\n"
"}")
        self.level_left_val.setInputMask("")
        self.level_left_val.setText("")
        self.level_left_val.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.level_left_val.setObjectName("level_left_val")
        self.patient_val = QtWidgets.QLineEdit(Form)
        self.patient_val.setGeometry(QtCore.QRect(740, 10, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.patient_val.setFont(font)
        self.patient_val.setStyleSheet("QLineEdit {\n"
"\n"
"background-color: \"white\"\n"
"\n"
"}")
        self.patient_val.setInputMask("")
        self.patient_val.setText("")
        self.patient_val.setObjectName("patient_val")
        self.patient = QtWidgets.QPlainTextEdit(Form)
        self.patient.setGeometry(QtCore.QRect(630, 10, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.patient.setFont(font)
        self.patient.setStyleSheet("QPlainTextEdit {\n"
"\n"
"background-color: \"white\"\n"
"\n"
"}")
        self.patient.setTextInteractionFlags(QtCore.Qt.TextInteractionFlag.NoTextInteraction)
        self.patient.setObjectName("patient")
        self.alias_val = QtWidgets.QLineEdit(Form)
        self.alias_val.setGeometry(QtCore.QRect(740, 40, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.alias_val.setFont(font)
        self.alias_val.setStyleSheet("QLineEdit {\n"
"\n"
"background-color: \"white\"\n"
"\n"
"}")
        self.alias_val.setInputMask("")
        self.alias_val.setText("")
        self.alias_val.setObjectName("alias_val")
        self.alias = QtWidgets.QPlainTextEdit(Form)
        self.alias.setGeometry(QtCore.QRect(630, 40, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.alias.setFont(font)
        self.alias.setStyleSheet("QPlainTextEdit {\n"
"\n"
"background-color: \"white\"\n"
"\n"
"}")
        self.alias.setTextInteractionFlags(QtCore.Qt.TextInteractionFlag.NoTextInteraction)
        self.alias.setObjectName("alias")
        self.hp_screws_val = QtWidgets.QLineEdit(Form)
        self.hp_screws_val.setGeometry(QtCore.QRect(1160, 320, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.hp_screws_val.setFont(font)
        self.hp_screws_val.setStyleSheet("QLineEdit {\n"
"\n"
"background-color: \"white\"\n"
"\n"
"}")
        self.hp_screws_val.setInputMask("")
        self.hp_screws_val.setText("")
        self.hp_screws_val.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.hp_screws_val.setObjectName("hp_screws_val")
        self.hp_screws = QtWidgets.QPlainTextEdit(Form)
        self.hp_screws.setGeometry(QtCore.QRect(1050, 320, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.hp_screws.setFont(font)
        self.hp_screws.setStyleSheet("QPlainTextEdit {\n"
"\n"
"background-color: \"white\"\n"
"\n"
"}")
        self.hp_screws.setTextInteractionFlags(QtCore.Qt.TextInteractionFlag.NoTextInteraction)
        self.hp_screws.setObjectName("hp_screws")
        self.hp_label = QtWidgets.QLabel(Form)
        self.hp_label.setGeometry(QtCore.QRect(1080, 240, 161, 51))
        font = QtGui.QFont()
        font.setPointSize(19)
        self.hp_label.setFont(font)
        self.hp_label.setStyleSheet("QLabel {\n"
"\n"
"    background-color: rgb(147, 147, 147);\n"
"\n"
"    border-color: rgb(0, 0, 0);\n"
"\n"
"}")
        self.hp_label.setFrameShape(QtWidgets.QFrame.Shape.Box)
        self.hp_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.hp_label.setTextInteractionFlags(QtCore.Qt.TextInteractionFlag.NoTextInteraction)
        self.hp_label.setObjectName("hp_label")
        self.hp_hashing_val = QtWidgets.QLineEdit(Form)
        self.hp_hashing_val.setGeometry(QtCore.QRect(1160, 360, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.hp_hashing_val.setFont(font)
        self.hp_hashing_val.setStyleSheet("QLineEdit {\n"
"\n"
"background-color: \"white\"\n"
"\n"
"}")
        self.hp_hashing_val.setInputMask("")
        self.hp_hashing_val.setText("")
        self.hp_hashing_val.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.hp_hashing_val.setObjectName("hp_hashing_val")
        self.hp_hashing = QtWidgets.QPlainTextEdit(Form)
        self.hp_hashing.setGeometry(QtCore.QRect(1050, 360, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.hp_hashing.setFont(font)
        self.hp_hashing.setToolTip("")
        self.hp_hashing.setStyleSheet("QPlainTextEdit {\n"
"\n"
"background-color: \"white\"\n"
"\n"
"}")
        self.hp_hashing.setTextInteractionFlags(QtCore.Qt.TextInteractionFlag.NoTextInteraction)
        self.hp_hashing.setObjectName("hp_hashing")
        self.grin_target = QtWidgets.QPlainTextEdit(Form)
        self.grin_target.setGeometry(QtCore.QRect(10, 480, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.grin_target.setFont(font)
        self.grin_target.setToolTip("")
        self.grin_target.setStyleSheet("QPlainTextEdit {\n"
"\n"
"background-color: \"white\"\n"
"\n"
"}")
        self.grin_target.setTextInteractionFlags(QtCore.Qt.TextInteractionFlag.NoTextInteraction)
        self.grin_target.setObjectName("grin_target")
        self.grin_target_val = QtWidgets.QLineEdit(Form)
        self.grin_target_val.setGeometry(QtCore.QRect(120, 480, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.grin_target_val.setFont(font)
        self.grin_target_val.setStyleSheet("QLineEdit {\n"
"\n"
"background-color: \"white\"\n"
"\n"
"}")
        self.grin_target_val.setInputMask("")
        self.grin_target_val.setText("")
        self.grin_target_val.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.grin_target_val.setObjectName("grin_target_val")
        self.grin_hs_val = QtWidgets.QLineEdit(Form)
        self.grin_hs_val.setGeometry(QtCore.QRect(120, 440, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.grin_hs_val.setFont(font)
        self.grin_hs_val.setStyleSheet("QLineEdit {\n"
"\n"
"background-color: \"white\"\n"
"\n"
"}")
        self.grin_hs_val.setInputMask("")
        self.grin_hs_val.setText("")
        self.grin_hs_val.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.grin_hs_val.setObjectName("grin_hs_val")
        self.grin_hs = QtWidgets.QPlainTextEdit(Form)
        self.grin_hs.setGeometry(QtCore.QRect(10, 440, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.grin_hs.setFont(font)
        self.grin_hs.setStyleSheet("QPlainTextEdit {\n"
"\n"
"background-color: \"white\"\n"
"\n"
"}")
        self.grin_hs.setReadOnly(True)
        self.grin_hs.setTextInteractionFlags(QtCore.Qt.TextInteractionFlag.NoTextInteraction)
        self.grin_hs.setObjectName("grin_hs")
        self.grin_label = QtWidgets.QLabel(Form)
        self.grin_label.setGeometry(QtCore.QRect(60, 380, 131, 51))
        font = QtGui.QFont()
        font.setPointSize(19)
        self.grin_label.setFont(font)
        self.grin_label.setStyleSheet("QLabel {\n"
"\n"
"    background-color: rgb(255, 255, 255);\n"
"\n"
"}")
        self.grin_label.setFrameShape(QtWidgets.QFrame.Shape.Box)
        self.grin_label.setObjectName("grin_label")
        self.grin_dv_val = QtWidgets.QLineEdit(Form)
        self.grin_dv_val.setGeometry(QtCore.QRect(120, 600, 131, 31))
        self.grin_dv_val.setStyleSheet("QLineEdit {\n"
"\n"
"background-color: \"white\"\n"
"\n"
"}")
        self.grin_dv_val.setInputMask("")
        self.grin_dv_val.setText("")
        self.grin_dv_val.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.grin_dv_val.setObjectName("grin_dv_val")
        self.grin_dv = QtWidgets.QPlainTextEdit(Form)
        self.grin_dv.setGeometry(QtCore.QRect(10, 600, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.grin_dv.setFont(font)
        self.grin_dv.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.grin_dv.setStyleSheet("QPlainTextEdit {\n"
"\n"
"background-color: \"white\"\n"
"\n"
"}")
        self.grin_dv.setTabChangesFocus(True)
        self.grin_dv.setTextInteractionFlags(QtCore.Qt.TextInteractionFlag.NoTextInteraction)
        self.grin_dv.setObjectName("grin_dv")
        self.grin_ml = QtWidgets.QPlainTextEdit(Form)
        self.grin_ml.setGeometry(QtCore.QRect(10, 560, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.grin_ml.setFont(font)
        self.grin_ml.setStyleSheet("QPlainTextEdit {\n"
"\n"
"background-color: \"white\"\n"
"\n"
"}")
        self.grin_ml.setTextInteractionFlags(QtCore.Qt.TextInteractionFlag.NoTextInteraction)
        self.grin_ml.setObjectName("grin_ml")
        self.grin_ml_val = QtWidgets.QLineEdit(Form)
        self.grin_ml_val.setGeometry(QtCore.QRect(120, 560, 131, 31))
        self.grin_ml_val.setStyleSheet("QLineEdit {\n"
"\n"
"background-color: \"white\"\n"
"\n"
"}")
        self.grin_ml_val.setInputMask("")
        self.grin_ml_val.setText("")
        self.grin_ml_val.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.grin_ml_val.setObjectName("grin_ml_val")
        self.grin_ap = QtWidgets.QPlainTextEdit(Form)
        self.grin_ap.setGeometry(QtCore.QRect(10, 520, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.grin_ap.setFont(font)
        self.grin_ap.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.grin_ap.setStyleSheet("QPlainTextEdit {\n"
"\n"
"background-color: \"white\"\n"
"\n"
"}")
        self.grin_ap.setTabChangesFocus(True)
        self.grin_ap.setTextInteractionFlags(QtCore.Qt.TextInteractionFlag.NoTextInteraction)
        self.grin_ap.setObjectName("grin_ap")
        self.grin_ap_val = QtWidgets.QLineEdit(Form)
        self.grin_ap_val.setGeometry(QtCore.QRect(120, 520, 131, 31))
        self.grin_ap_val.setStyleSheet("QLineEdit {\n"
"\n"
"background-color: \"white\"\n"
"\n"
"}")
        self.grin_ap_val.setInputMask("")
        self.grin_ap_val.setText("")
        self.grin_ap_val.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.grin_ap_val.setObjectName("grin_ap_val")
        self.grin_angle_val = QtWidgets.QLineEdit(Form)
        self.grin_angle_val.setGeometry(QtCore.QRect(120, 640, 131, 31))
        self.grin_angle_val.setStyleSheet("QLineEdit {\n"
"\n"
"background-color: \"white\"\n"
"\n"
"}")
        self.grin_angle_val.setInputMask("")
        self.grin_angle_val.setText("")
        self.grin_angle_val.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.grin_angle_val.setObjectName("grin_angle_val")
        self.grin_angle = QtWidgets.QPlainTextEdit(Form)
        self.grin_angle.setGeometry(QtCore.QRect(10, 640, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.grin_angle.setFont(font)
        self.grin_angle.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.grin_angle.setStyleSheet("QPlainTextEdit {\n"
"\n"
"background-color: \"white\"\n"
"\n"
"}")
        self.grin_angle.setTabChangesFocus(True)
        self.grin_angle.setTextInteractionFlags(QtCore.Qt.TextInteractionFlag.NoTextInteraction)
        self.grin_angle.setObjectName("grin_angle")
        self.grin_notes = QtWidgets.QTextEdit(Form)
        self.grin_notes.setGeometry(QtCore.QRect(10, 680, 241, 71))
        self.grin_notes.setStyleSheet("QTextEdit {\n"
"\n"
"background-color: \"white\"\n"
"\n"
"}")
        self.grin_notes.setCursorWidth(1)
        self.grin_notes.setObjectName("grin_notes")
        self.gcamp_target_val = QtWidgets.QLineEdit(Form)
        self.gcamp_target_val.setGeometry(QtCore.QRect(380, 360, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.gcamp_target_val.setFont(font)
        self.gcamp_target_val.setStyleSheet("QLineEdit {\n"
"\n"
"background-color: \"white\"\n"
"\n"
"}")
        self.gcamp_target_val.setInputMask("")
        self.gcamp_target_val.setText("")
        self.gcamp_target_val.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.gcamp_target_val.setObjectName("gcamp_target_val")
        self.gcamp_val = QtWidgets.QPlainTextEdit(Form)
        self.gcamp_val.setGeometry(QtCore.QRect(270, 480, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.gcamp_val.setFont(font)
        self.gcamp_val.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.gcamp_val.setStyleSheet("QPlainTextEdit {\n"
"\n"
"background-color: \"white\"\n"
"\n"
"}")
        self.gcamp_val.setTabChangesFocus(True)
        self.gcamp_val.setTextInteractionFlags(QtCore.Qt.TextInteractionFlag.NoTextInteraction)
        self.gcamp_val.setObjectName("gcamp_val")
        self.gcamp_dv_val = QtWidgets.QLineEdit(Form)
        self.gcamp_dv_val.setGeometry(QtCore.QRect(380, 480, 131, 31))
        self.gcamp_dv_val.setStyleSheet("QLineEdit {\n"
"\n"
"background-color: \"white\"\n"
"\n"
"}")
        self.gcamp_dv_val.setInputMask("")
        self.gcamp_dv_val.setText("")
        self.gcamp_dv_val.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.gcamp_dv_val.setObjectName("gcamp_dv_val")
        self.gcamp_hs_val = QtWidgets.QLineEdit(Form)
        self.gcamp_hs_val.setGeometry(QtCore.QRect(380, 320, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.gcamp_hs_val.setFont(font)
        self.gcamp_hs_val.setStyleSheet("QLineEdit {\n"
"\n"
"background-color: \"white\"\n"
"\n"
"}")
        self.gcamp_hs_val.setInputMask("")
        self.gcamp_hs_val.setText("")
        self.gcamp_hs_val.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.gcamp_hs_val.setObjectName("gcamp_hs_val")
        self.gcamp_hs = QtWidgets.QPlainTextEdit(Form)
        self.gcamp_hs.setGeometry(QtCore.QRect(270, 320, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.gcamp_hs.setFont(font)
        self.gcamp_hs.setToolTip("")
        self.gcamp_hs.setStyleSheet("QPlainTextEdit {\n"
"\n"
"background-color: \"white\"\n"
"\n"
"}")
        self.gcamp_hs.setTextInteractionFlags(QtCore.Qt.TextInteractionFlag.NoTextInteraction)
        self.gcamp_hs.setObjectName("gcamp_hs")
        self.gcamp_ml_val = QtWidgets.QLineEdit(Form)
        self.gcamp_ml_val.setGeometry(QtCore.QRect(380, 440, 131, 31))
        self.gcamp_ml_val.setStyleSheet("QLineEdit {\n"
"\n"
"background-color: \"white\"\n"
"\n"
"}")
        self.gcamp_ml_val.setInputMask("")
        self.gcamp_ml_val.setText("")
        self.gcamp_ml_val.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.gcamp_ml_val.setObjectName("gcamp_ml_val")
        self.gcamp_angle_val = QtWidgets.QLineEdit(Form)
        self.gcamp_angle_val.setGeometry(QtCore.QRect(380, 520, 131, 31))
        self.gcamp_angle_val.setStyleSheet("QLineEdit {\n"
"\n"
"background-color: \"white\"\n"
"\n"
"}")
        self.gcamp_angle_val.setInputMask("")
        self.gcamp_angle_val.setText("")
        self.gcamp_angle_val.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.gcamp_angle_val.setObjectName("gcamp_angle_val")
        self.gcamp_ap_val = QtWidgets.QLineEdit(Form)
        self.gcamp_ap_val.setGeometry(QtCore.QRect(380, 400, 131, 31))
        self.gcamp_ap_val.setStyleSheet("QLineEdit {\n"
"\n"
"background-color: \"white\"\n"
"\n"
"}")
        self.gcamp_ap_val.setInputMask("")
        self.gcamp_ap_val.setText("")
        self.gcamp_ap_val.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.gcamp_ap_val.setObjectName("gcamp_ap_val")
        self.gcamp_ap = QtWidgets.QPlainTextEdit(Form)
        self.gcamp_ap.setGeometry(QtCore.QRect(270, 400, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.gcamp_ap.setFont(font)
        self.gcamp_ap.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.gcamp_ap.setStyleSheet("QPlainTextEdit {\n"
"\n"
"background-color: \"white\"\n"
"\n"
"}")
        self.gcamp_ap.setTabChangesFocus(True)
        self.gcamp_ap.setTextInteractionFlags(QtCore.Qt.TextInteractionFlag.NoTextInteraction)
        self.gcamp_ap.setObjectName("gcamp_ap")
        self.gcamp_notes = QtWidgets.QTextEdit(Form)
        self.gcamp_notes.setGeometry(QtCore.QRect(270, 680, 241, 71))
        self.gcamp_notes.setStyleSheet("QTextEdit {\n"
"\n"
"background-color: \"white\"\n"
"\n"
"}")
        self.gcamp_notes.setCursorWidth(1)
        self.gcamp_notes.setObjectName("gcamp_notes")
        self.gcamp_label = QtWidgets.QLabel(Form)
        self.gcamp_label.setGeometry(QtCore.QRect(300, 240, 161, 51))
        font = QtGui.QFont()
        font.setPointSize(19)
        self.gcamp_label.setFont(font)
        self.gcamp_label.setStyleSheet("QLabel {\n"
"\n"
"    background-color: rgb(80, 255, 49);\n"
"    \n"
"    border-color: rgb(0, 255, 0);\n"
"\n"
"}")
        self.gcamp_label.setFrameShape(QtWidgets.QFrame.Shape.Box)
        self.gcamp_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.gcamp_label.setTextInteractionFlags(QtCore.Qt.TextInteractionFlag.NoTextInteraction)
        self.gcamp_label.setObjectName("gcamp_label")
        self.gcamp_angle = QtWidgets.QPlainTextEdit(Form)
        self.gcamp_angle.setGeometry(QtCore.QRect(270, 520, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.gcamp_angle.setFont(font)
        self.gcamp_angle.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.gcamp_angle.setStyleSheet("QPlainTextEdit {\n"
"\n"
"background-color: \"white\"\n"
"\n"
"}")
        self.gcamp_angle.setTabChangesFocus(True)
        self.gcamp_angle.setTextInteractionFlags(QtCore.Qt.TextInteractionFlag.NoTextInteraction)
        self.gcamp_angle.setObjectName("gcamp_angle")
        self.gcamp_ml = QtWidgets.QPlainTextEdit(Form)
        self.gcamp_ml.setGeometry(QtCore.QRect(270, 440, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.gcamp_ml.setFont(font)
        self.gcamp_ml.setStyleSheet("QPlainTextEdit {\n"
"\n"
"background-color: \"white\"\n"
"\n"
"}")
        self.gcamp_ml.setTextInteractionFlags(QtCore.Qt.TextInteractionFlag.NoTextInteraction)
        self.gcamp_ml.setObjectName("gcamp_ml")
        self.gcamp_target = QtWidgets.QPlainTextEdit(Form)
        self.gcamp_target.setGeometry(QtCore.QRect(270, 360, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.gcamp_target.setFont(font)
        self.gcamp_target.setToolTip("")
        self.gcamp_target.setStyleSheet("QPlainTextEdit {\n"
"\n"
"background-color: \"white\"\n"
"\n"
"}")
        self.gcamp_target.setTextInteractionFlags(QtCore.Qt.TextInteractionFlag.NoTextInteraction)
        self.gcamp_target.setObjectName("gcamp_target")
        self.chr_angle = QtWidgets.QPlainTextEdit(Form)
        self.chr_angle.setGeometry(QtCore.QRect(530, 520, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.chr_angle.setFont(font)
        self.chr_angle.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.chr_angle.setStyleSheet("QPlainTextEdit {\n"
"\n"
"background-color: \"white\"\n"
"\n"
"}")
        self.chr_angle.setTabChangesFocus(True)
        self.chr_angle.setTextInteractionFlags(QtCore.Qt.TextInteractionFlag.NoTextInteraction)
        self.chr_angle.setObjectName("chr_angle")
        self.chr_ml = QtWidgets.QPlainTextEdit(Form)
        self.chr_ml.setGeometry(QtCore.QRect(530, 440, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.chr_ml.setFont(font)
        self.chr_ml.setStyleSheet("QPlainTextEdit {\n"
"\n"
"background-color: \"white\"\n"
"\n"
"}")
        self.chr_ml.setTextInteractionFlags(QtCore.Qt.TextInteractionFlag.NoTextInteraction)
        self.chr_ml.setObjectName("chr_ml")
        self.chr_label = QtWidgets.QLabel(Form)
        self.chr_label.setGeometry(QtCore.QRect(560, 240, 161, 51))
        font = QtGui.QFont()
        font.setPointSize(19)
        self.chr_label.setFont(font)
        self.chr_label.setStyleSheet("QLabel {\n"
"\n"
"    background-color: rgb(76, 183, 255)\n"
"\n"
"}")
        self.chr_label.setFrameShape(QtWidgets.QFrame.Shape.Box)
        self.chr_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.chr_label.setTextInteractionFlags(QtCore.Qt.TextInteractionFlag.NoTextInteraction)
        self.chr_label.setObjectName("chr_label")
        self.chr_notes = QtWidgets.QTextEdit(Form)
        self.chr_notes.setGeometry(QtCore.QRect(530, 680, 241, 71))
        self.chr_notes.setStyleSheet("QTextEdit {\n"
"\n"
"background-color: \"white\"\n"
"\n"
"}")
        self.chr_notes.setCursorWidth(1)
        self.chr_notes.setObjectName("chr_notes")
        self.chr_ap_val = QtWidgets.QLineEdit(Form)
        self.chr_ap_val.setGeometry(QtCore.QRect(640, 400, 131, 31))
        self.chr_ap_val.setStyleSheet("QLineEdit {\n"
"\n"
"background-color: \"white\"\n"
"\n"
"}")
        self.chr_ap_val.setInputMask("")
        self.chr_ap_val.setText("")
        self.chr_ap_val.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.chr_ap_val.setObjectName("chr_ap_val")
        self.chr_angle_val = QtWidgets.QLineEdit(Form)
        self.chr_angle_val.setGeometry(QtCore.QRect(640, 520, 131, 31))
        self.chr_angle_val.setStyleSheet("QLineEdit {\n"
"\n"
"background-color: \"white\"\n"
"\n"
"}")
        self.chr_angle_val.setInputMask("")
        self.chr_angle_val.setText("")
        self.chr_angle_val.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.chr_angle_val.setObjectName("chr_angle_val")
        self.chr_dv_val = QtWidgets.QLineEdit(Form)
        self.chr_dv_val.setGeometry(QtCore.QRect(640, 480, 131, 31))
        self.chr_dv_val.setStyleSheet("QLineEdit {\n"
"\n"
"background-color: \"white\"\n"
"\n"
"}")
        self.chr_dv_val.setInputMask("")
        self.chr_dv_val.setText("")
        self.chr_dv_val.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.chr_dv_val.setObjectName("chr_dv_val")
        self.chr_hs_val = QtWidgets.QLineEdit(Form)
        self.chr_hs_val.setGeometry(QtCore.QRect(640, 320, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.chr_hs_val.setFont(font)
        self.chr_hs_val.setStyleSheet("QLineEdit {\n"
"\n"
"background-color: \"white\"\n"
"\n"
"}")
        self.chr_hs_val.setInputMask("")
        self.chr_hs_val.setText("")
        self.chr_hs_val.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.chr_hs_val.setObjectName("chr_hs_val")
        self.chr_target = QtWidgets.QPlainTextEdit(Form)
        self.chr_target.setGeometry(QtCore.QRect(530, 360, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.chr_target.setFont(font)
        self.chr_target.setToolTip("")
        self.chr_target.setStyleSheet("QPlainTextEdit {\n"
"\n"
"background-color: \"white\"\n"
"\n"
"}")
        self.chr_target.setTextInteractionFlags(QtCore.Qt.TextInteractionFlag.NoTextInteraction)
        self.chr_target.setObjectName("chr_target")
        self.chr_ap = QtWidgets.QPlainTextEdit(Form)
        self.chr_ap.setGeometry(QtCore.QRect(530, 400, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.chr_ap.setFont(font)
        self.chr_ap.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.chr_ap.setStyleSheet("QPlainTextEdit {\n"
"\n"
"background-color: \"white\"\n"
"\n"
"}")
        self.chr_ap.setTabChangesFocus(True)
        self.chr_ap.setTextInteractionFlags(QtCore.Qt.TextInteractionFlag.NoTextInteraction)
        self.chr_ap.setObjectName("chr_ap")
        self.chr_dv = QtWidgets.QPlainTextEdit(Form)
        self.chr_dv.setGeometry(QtCore.QRect(530, 480, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.chr_dv.setFont(font)
        self.chr_dv.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.chr_dv.setStyleSheet("QPlainTextEdit {\n"
"\n"
"background-color: \"white\"\n"
"\n"
"}")
        self.chr_dv.setTabChangesFocus(True)
        self.chr_dv.setTextInteractionFlags(QtCore.Qt.TextInteractionFlag.NoTextInteraction)
        self.chr_dv.setObjectName("chr_dv")
        self.chr_ml_val = QtWidgets.QLineEdit(Form)
        self.chr_ml_val.setGeometry(QtCore.QRect(640, 440, 131, 31))
        self.chr_ml_val.setStyleSheet("QLineEdit {\n"
"\n"
"background-color: \"white\"\n"
"\n"
"}")
        self.chr_ml_val.setInputMask("")
        self.chr_ml_val.setText("")
        self.chr_ml_val.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.chr_ml_val.setObjectName("chr_ml_val")
        self.chr_target_val = QtWidgets.QLineEdit(Form)
        self.chr_target_val.setGeometry(QtCore.QRect(640, 360, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.chr_target_val.setFont(font)
        self.chr_target_val.setStyleSheet("QLineEdit {\n"
"\n"
"background-color: \"white\"\n"
"\n"
"}")
        self.chr_target_val.setInputMask("")
        self.chr_target_val.setText("")
        self.chr_target_val.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.chr_target_val.setObjectName("chr_target_val")
        self.chr_hs = QtWidgets.QPlainTextEdit(Form)
        self.chr_hs.setGeometry(QtCore.QRect(530, 320, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.chr_hs.setFont(font)
        self.chr_hs.setToolTip("")
        self.chr_hs.setStyleSheet("QPlainTextEdit {\n"
"\n"
"background-color: \"white\"\n"
"\n"
"}")
        self.chr_hs.setTextInteractionFlags(QtCore.Qt.TextInteractionFlag.NoTextInteraction)
        self.chr_hs.setObjectName("chr_hs")
        self.tracer_angle_val = QtWidgets.QLineEdit(Form)
        self.tracer_angle_val.setGeometry(QtCore.QRect(900, 520, 131, 31))
        self.tracer_angle_val.setStyleSheet("QLineEdit {\n"
"\n"
"background-color: \"white\"\n"
"\n"
"}")
        self.tracer_angle_val.setInputMask("")
        self.tracer_angle_val.setText("")
        self.tracer_angle_val.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.tracer_angle_val.setObjectName("tracer_angle_val")
        self.tracer_ml = QtWidgets.QPlainTextEdit(Form)
        self.tracer_ml.setGeometry(QtCore.QRect(790, 440, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.tracer_ml.setFont(font)
        self.tracer_ml.setStyleSheet("QPlainTextEdit {\n"
"\n"
"background-color: \"white\"\n"
"\n"
"}")
        self.tracer_ml.setTextInteractionFlags(QtCore.Qt.TextInteractionFlag.NoTextInteraction)
        self.tracer_ml.setObjectName("tracer_ml")
        self.tracer_ap_val = QtWidgets.QLineEdit(Form)
        self.tracer_ap_val.setGeometry(QtCore.QRect(900, 400, 131, 31))
        self.tracer_ap_val.setStyleSheet("QLineEdit {\n"
"\n"
"background-color: \"white\"\n"
"\n"
"}")
        self.tracer_ap_val.setInputMask("")
        self.tracer_ap_val.setText("")
        self.tracer_ap_val.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.tracer_ap_val.setObjectName("tracer_ap_val")
        self.tracer_ap = QtWidgets.QPlainTextEdit(Form)
        self.tracer_ap.setGeometry(QtCore.QRect(790, 400, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.tracer_ap.setFont(font)
        self.tracer_ap.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.tracer_ap.setStyleSheet("QPlainTextEdit {\n"
"\n"
"background-color: \"white\"\n"
"\n"
"}")
        self.tracer_ap.setTabChangesFocus(True)
        self.tracer_ap.setTextInteractionFlags(QtCore.Qt.TextInteractionFlag.NoTextInteraction)
        self.tracer_ap.setObjectName("tracer_ap")
        self.tracer_dv = QtWidgets.QPlainTextEdit(Form)
        self.tracer_dv.setGeometry(QtCore.QRect(790, 480, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.tracer_dv.setFont(font)
        self.tracer_dv.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.tracer_dv.setStyleSheet("QPlainTextEdit {\n"
"\n"
"background-color: \"white\"\n"
"\n"
"}")
        self.tracer_dv.setTabChangesFocus(True)
        self.tracer_dv.setTextInteractionFlags(QtCore.Qt.TextInteractionFlag.NoTextInteraction)
        self.tracer_dv.setObjectName("tracer_dv")
        self.tracer_target = QtWidgets.QPlainTextEdit(Form)
        self.tracer_target.setGeometry(QtCore.QRect(790, 360, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.tracer_target.setFont(font)
        self.tracer_target.setToolTip("")
        self.tracer_target.setStyleSheet("QPlainTextEdit {\n"
"\n"
"background-color: \"white\"\n"
"\n"
"}")
        self.tracer_target.setTextInteractionFlags(QtCore.Qt.TextInteractionFlag.NoTextInteraction)
        self.tracer_target.setObjectName("tracer_target")
        self.tracer_dv_val = QtWidgets.QLineEdit(Form)
        self.tracer_dv_val.setGeometry(QtCore.QRect(900, 480, 131, 31))
        self.tracer_dv_val.setStyleSheet("QLineEdit {\n"
"\n"
"background-color: \"white\"\n"
"\n"
"}")
        self.tracer_dv_val.setInputMask("")
        self.tracer_dv_val.setText("")
        self.tracer_dv_val.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.tracer_dv_val.setObjectName("tracer_dv_val")
        self.tracer_ml_val = QtWidgets.QLineEdit(Form)
        self.tracer_ml_val.setGeometry(QtCore.QRect(900, 440, 131, 31))
        self.tracer_ml_val.setStyleSheet("QLineEdit {\n"
"\n"
"background-color: \"white\"\n"
"\n"
"}")
        self.tracer_ml_val.setInputMask("")
        self.tracer_ml_val.setText("")
        self.tracer_ml_val.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.tracer_ml_val.setObjectName("tracer_ml_val")
        self.tracer_hs_val = QtWidgets.QLineEdit(Form)
        self.tracer_hs_val.setGeometry(QtCore.QRect(900, 320, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.tracer_hs_val.setFont(font)
        self.tracer_hs_val.setStyleSheet("QLineEdit {\n"
"\n"
"background-color: \"white\"\n"
"\n"
"}")
        self.tracer_hs_val.setInputMask("")
        self.tracer_hs_val.setText("")
        self.tracer_hs_val.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.tracer_hs_val.setObjectName("tracer_hs_val")
        self.tracer_target_val = QtWidgets.QLineEdit(Form)
        self.tracer_target_val.setGeometry(QtCore.QRect(900, 360, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.tracer_target_val.setFont(font)
        self.tracer_target_val.setStyleSheet("QLineEdit {\n"
"\n"
"background-color: \"white\"\n"
"\n"
"}")
        self.tracer_target_val.setInputMask("")
        self.tracer_target_val.setText("")
        self.tracer_target_val.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.tracer_target_val.setObjectName("tracer_target_val")
        self.tracer_label = QtWidgets.QLabel(Form)
        self.tracer_label.setGeometry(QtCore.QRect(830, 240, 161, 51))
        font = QtGui.QFont()
        font.setPointSize(19)
        self.tracer_label.setFont(font)
        self.tracer_label.setStyleSheet("QLabel {\n"
"\n"
"    background-color: rgb(255, 60, 63);\n"
"\n"
"}")
        self.tracer_label.setFrameShape(QtWidgets.QFrame.Shape.Box)
        self.tracer_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.tracer_label.setTextInteractionFlags(QtCore.Qt.TextInteractionFlag.NoTextInteraction)
        self.tracer_label.setObjectName("tracer_label")
        self.tracer_angle = QtWidgets.QPlainTextEdit(Form)
        self.tracer_angle.setGeometry(QtCore.QRect(790, 520, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.tracer_angle.setFont(font)
        self.tracer_angle.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.tracer_angle.setStyleSheet("QPlainTextEdit {\n"
"\n"
"background-color: \"white\"\n"
"\n"
"}")
        self.tracer_angle.setTabChangesFocus(True)
        self.tracer_angle.setTextInteractionFlags(QtCore.Qt.TextInteractionFlag.NoTextInteraction)
        self.tracer_angle.setObjectName("tracer_angle")
        self.tracer_notes = QtWidgets.QTextEdit(Form)
        self.tracer_notes.setGeometry(QtCore.QRect(790, 680, 241, 71))
        self.tracer_notes.setStyleSheet("QTextEdit {\n"
"\n"
"background-color: \"white\"\n"
"\n"
"}")
        self.tracer_notes.setCursorWidth(1)
        self.tracer_notes.setObjectName("tracer_notes")
        self.tracer_hs = QtWidgets.QPlainTextEdit(Form)
        self.tracer_hs.setGeometry(QtCore.QRect(790, 320, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.tracer_hs.setFont(font)
        self.tracer_hs.setToolTip("")
        self.tracer_hs.setStyleSheet("QPlainTextEdit {\n"
"\n"
"background-color: \"white\"\n"
"\n"
"}")
        self.tracer_hs.setTextInteractionFlags(QtCore.Qt.TextInteractionFlag.NoTextInteraction)
        self.tracer_hs.setObjectName("tracer_hs")
        self.greeting_label = QtWidgets.QLabel(Form)
        self.greeting_label.setGeometry(QtCore.QRect(10, 10, 341, 61))
        font = QtGui.QFont()
        font.setPointSize(30)
        self.greeting_label.setFont(font)
        self.greeting_label.setStyleSheet("")
        self.greeting_label.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.greeting_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.greeting_label.setObjectName("greeting_label")
        self.leveling_label = QtWidgets.QLabel(Form)
        self.leveling_label.setGeometry(QtCore.QRect(10, 140, 241, 51))
        font = QtGui.QFont()
        font.setPointSize(19)
        self.leveling_label.setFont(font)
        self.leveling_label.setStyleSheet("QLabel {\n"
"\n"
"    background-color: rgb(255, 255, 255);\n"
"\n"
"    border-color: rgb(0, 0, 0);\n"
"\n"
"}")
        self.leveling_label.setFrameShape(QtWidgets.QFrame.Shape.Box)
        self.leveling_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.leveling_label.setObjectName("leveling_label")
        self.gcamp_vol = QtWidgets.QPlainTextEdit(Form)
        self.gcamp_vol.setGeometry(QtCore.QRect(270, 560, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.gcamp_vol.setFont(font)
        self.gcamp_vol.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.gcamp_vol.setStyleSheet("QPlainTextEdit {\n"
"\n"
"background-color: \"white\"\n"
"\n"
"}")
        self.gcamp_vol.setTabChangesFocus(True)
        self.gcamp_vol.setTextInteractionFlags(QtCore.Qt.TextInteractionFlag.NoTextInteraction)
        self.gcamp_vol.setObjectName("gcamp_vol")
        self.gcamp_vol_val = QtWidgets.QLineEdit(Form)
        self.gcamp_vol_val.setGeometry(QtCore.QRect(380, 560, 131, 31))
        self.gcamp_vol_val.setStyleSheet("QLineEdit {\n"
"\n"
"background-color: \"white\"\n"
"\n"
"}")
        self.gcamp_vol_val.setInputMask("")
        self.gcamp_vol_val.setText("")
        self.gcamp_vol_val.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.gcamp_vol_val.setObjectName("gcamp_vol_val")
        self.gcamp_rate_val = QtWidgets.QLineEdit(Form)
        self.gcamp_rate_val.setGeometry(QtCore.QRect(380, 600, 131, 31))
        self.gcamp_rate_val.setStyleSheet("QLineEdit {\n"
"\n"
"background-color: \"white\"\n"
"\n"
"}")
        self.gcamp_rate_val.setInputMask("")
        self.gcamp_rate_val.setText("")
        self.gcamp_rate_val.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.gcamp_rate_val.setObjectName("gcamp_rate_val")
        self.gcamp_rate = QtWidgets.QPlainTextEdit(Form)
        self.gcamp_rate.setGeometry(QtCore.QRect(270, 600, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.gcamp_rate.setFont(font)
        self.gcamp_rate.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.gcamp_rate.setStyleSheet("QPlainTextEdit {\n"
"\n"
"background-color: \"white\"\n"
"\n"
"}")
        self.gcamp_rate.setTabChangesFocus(True)
        self.gcamp_rate.setTextInteractionFlags(QtCore.Qt.TextInteractionFlag.NoTextInteraction)
        self.gcamp_rate.setObjectName("gcamp_rate")
        self.gcamp_bevel_val = QtWidgets.QLineEdit(Form)
        self.gcamp_bevel_val.setGeometry(QtCore.QRect(380, 640, 131, 31))
        self.gcamp_bevel_val.setStyleSheet("QLineEdit {\n"
"\n"
"background-color: \"white\"\n"
"\n"
"}")
        self.gcamp_bevel_val.setInputMask("")
        self.gcamp_bevel_val.setText("")
        self.gcamp_bevel_val.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.gcamp_bevel_val.setObjectName("gcamp_bevel_val")
        self.gcamp_bevel = QtWidgets.QPlainTextEdit(Form)
        self.gcamp_bevel.setGeometry(QtCore.QRect(270, 640, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.gcamp_bevel.setFont(font)
        self.gcamp_bevel.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.gcamp_bevel.setStyleSheet("QPlainTextEdit {\n"
"\n"
"background-color: \"white\"\n"
"\n"
"}")
        self.gcamp_bevel.setTabChangesFocus(True)
        self.gcamp_bevel.setTextInteractionFlags(QtCore.Qt.TextInteractionFlag.NoTextInteraction)
        self.gcamp_bevel.setObjectName("gcamp_bevel")
        self.chr_vol_val = QtWidgets.QLineEdit(Form)
        self.chr_vol_val.setGeometry(QtCore.QRect(640, 560, 131, 31))
        self.chr_vol_val.setStyleSheet("QLineEdit {\n"
"\n"
"background-color: \"white\"\n"
"\n"
"}")
        self.chr_vol_val.setInputMask("")
        self.chr_vol_val.setText("")
        self.chr_vol_val.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.chr_vol_val.setObjectName("chr_vol_val")
        self.chr_vol = QtWidgets.QPlainTextEdit(Form)
        self.chr_vol.setGeometry(QtCore.QRect(530, 560, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.chr_vol.setFont(font)
        self.chr_vol.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.chr_vol.setStyleSheet("QPlainTextEdit {\n"
"\n"
"background-color: \"white\"\n"
"\n"
"}")
        self.chr_vol.setTabChangesFocus(True)
        self.chr_vol.setTextInteractionFlags(QtCore.Qt.TextInteractionFlag.NoTextInteraction)
        self.chr_vol.setObjectName("chr_vol")
        self.chr_rate_val = QtWidgets.QLineEdit(Form)
        self.chr_rate_val.setGeometry(QtCore.QRect(640, 600, 131, 31))
        self.chr_rate_val.setStyleSheet("QLineEdit {\n"
"\n"
"background-color: \"white\"\n"
"\n"
"}")
        self.chr_rate_val.setInputMask("")
        self.chr_rate_val.setText("")
        self.chr_rate_val.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.chr_rate_val.setObjectName("chr_rate_val")
        self.chr_bevel_val = QtWidgets.QLineEdit(Form)
        self.chr_bevel_val.setGeometry(QtCore.QRect(640, 640, 131, 31))
        self.chr_bevel_val.setStyleSheet("QLineEdit {\n"
"\n"
"background-color: \"white\"\n"
"\n"
"}")
        self.chr_bevel_val.setInputMask("")
        self.chr_bevel_val.setText("")
        self.chr_bevel_val.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.chr_bevel_val.setObjectName("chr_bevel_val")
        self.chr_rate = QtWidgets.QPlainTextEdit(Form)
        self.chr_rate.setGeometry(QtCore.QRect(530, 600, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.chr_rate.setFont(font)
        self.chr_rate.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.chr_rate.setStyleSheet("QPlainTextEdit {\n"
"\n"
"background-color: \"white\"\n"
"\n"
"}")
        self.chr_rate.setTabChangesFocus(True)
        self.chr_rate.setTextInteractionFlags(QtCore.Qt.TextInteractionFlag.NoTextInteraction)
        self.chr_rate.setObjectName("chr_rate")
        self.chr_bevel = QtWidgets.QPlainTextEdit(Form)
        self.chr_bevel.setGeometry(QtCore.QRect(530, 640, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.chr_bevel.setFont(font)
        self.chr_bevel.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.chr_bevel.setStyleSheet("QPlainTextEdit {\n"
"\n"
"background-color: \"white\"\n"
"\n"
"}")
        self.chr_bevel.setTabChangesFocus(True)
        self.chr_bevel.setTextInteractionFlags(QtCore.Qt.TextInteractionFlag.NoTextInteraction)
        self.chr_bevel.setObjectName("chr_bevel")
        self.tracer_rate = QtWidgets.QPlainTextEdit(Form)
        self.tracer_rate.setGeometry(QtCore.QRect(790, 600, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.tracer_rate.setFont(font)
        self.tracer_rate.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.tracer_rate.setStyleSheet("QPlainTextEdit {\n"
"\n"
"background-color: \"white\"\n"
"\n"
"}")
        self.tracer_rate.setTabChangesFocus(True)
        self.tracer_rate.setTextInteractionFlags(QtCore.Qt.TextInteractionFlag.NoTextInteraction)
        self.tracer_rate.setObjectName("tracer_rate")
        self.tracer_bevel_val = QtWidgets.QLineEdit(Form)
        self.tracer_bevel_val.setGeometry(QtCore.QRect(900, 640, 131, 31))
        self.tracer_bevel_val.setStyleSheet("QLineEdit {\n"
"\n"
"background-color: \"white\"\n"
"\n"
"}")
        self.tracer_bevel_val.setInputMask("")
        self.tracer_bevel_val.setText("")
        self.tracer_bevel_val.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.tracer_bevel_val.setObjectName("tracer_bevel_val")
        self.tracer_vol_rate = QtWidgets.QLineEdit(Form)
        self.tracer_vol_rate.setGeometry(QtCore.QRect(900, 600, 131, 31))
        self.tracer_vol_rate.setStyleSheet("QLineEdit {\n"
"\n"
"background-color: \"white\"\n"
"\n"
"}")
        self.tracer_vol_rate.setInputMask("")
        self.tracer_vol_rate.setText("")
        self.tracer_vol_rate.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.tracer_vol_rate.setObjectName("tracer_vol_rate")
        self.tracer_vol = QtWidgets.QPlainTextEdit(Form)
        self.tracer_vol.setGeometry(QtCore.QRect(790, 560, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.tracer_vol.setFont(font)
        self.tracer_vol.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.tracer_vol.setStyleSheet("QPlainTextEdit {\n"
"\n"
"background-color: \"white\"\n"
"\n"
"}")
        self.tracer_vol.setTabChangesFocus(True)
        self.tracer_vol.setTextInteractionFlags(QtCore.Qt.TextInteractionFlag.NoTextInteraction)
        self.tracer_vol.setObjectName("tracer_vol")
        self.tracer_bevel = QtWidgets.QPlainTextEdit(Form)
        self.tracer_bevel.setGeometry(QtCore.QRect(790, 640, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.tracer_bevel.setFont(font)
        self.tracer_bevel.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.tracer_bevel.setStyleSheet("QPlainTextEdit {\n"
"\n"
"background-color: \"white\"\n"
"\n"
"}")
        self.tracer_bevel.setTabChangesFocus(True)
        self.tracer_bevel.setTextInteractionFlags(QtCore.Qt.TextInteractionFlag.NoTextInteraction)
        self.tracer_bevel.setObjectName("tracer_bevel")
        self.tracer_vol_val = QtWidgets.QLineEdit(Form)
        self.tracer_vol_val.setGeometry(QtCore.QRect(900, 560, 131, 31))
        self.tracer_vol_val.setStyleSheet("QLineEdit {\n"
"\n"
"background-color: \"white\"\n"
"\n"
"}")
        self.tracer_vol_val.setInputMask("")
        self.tracer_vol_val.setText("")
        self.tracer_vol_val.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.tracer_vol_val.setObjectName("tracer_vol_val")
        self.hp_notes = QtWidgets.QTextEdit(Form)
        self.hp_notes.setGeometry(QtCore.QRect(1050, 400, 241, 71))
        self.hp_notes.setStyleSheet("QTextEdit {\n"
"\n"
"background-color: \"white\"\n"
"\n"
"}")
        self.hp_notes.setCursorWidth(1)
        self.hp_notes.setObjectName("hp_notes")
        self.death_notes = QtWidgets.QTextEdit(Form)
        self.death_notes.setGeometry(QtCore.QRect(920, 10, 241, 91))
        self.death_notes.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.CursorShape.ArrowCursor))
        self.death_notes.setStyleSheet("QTextEdit {\n"
"\n"
"background-color: \"white\"\n"
"\n"
"}")
        self.death_notes.setCursorWidth(1)
        self.death_notes.setObjectName("death_notes")
        self.death_btn = QtWidgets.QPushButton(Form)
        self.death_btn.setGeometry(QtCore.QRect(1180, 10, 131, 91))
        self.death_btn.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.CrossCursor))
        self.death_btn.setStyleSheet("QPushButton{\n"
"\n"
"    background-color: rgb(0, 0, 0);\n"
"\n"
"    color: rgb(255, 255, 255);\n"
"\n"
"}")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("death_icon.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.death_btn.setIcon(icon)
        self.death_btn.setShortcut("")
        self.death_btn.setDefault(True)
        self.death_btn.setFlat(False)
        self.death_btn.setObjectName("death_btn")
        self.weight_val = QtWidgets.QLineEdit(Form)
        self.weight_val.setGeometry(QtCore.QRect(740, 70, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.weight_val.setFont(font)
        self.weight_val.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.ArrowCursor))
        self.weight_val.setStyleSheet("QLineEdit {\n"
"\n"
"background-color: \"white\"\n"
"\n"
"}")
        self.weight_val.setInputMask("")
        self.weight_val.setText("")
        self.weight_val.setObjectName("weight_val")
        self.project_2 = QtWidgets.QPlainTextEdit(Form)
        self.project_2.setGeometry(QtCore.QRect(630, 70, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.project_2.setFont(font)
        self.project_2.setStyleSheet("QPlainTextEdit {\n"
"\n"
"background-color: \"white\"\n"
"\n"
"}")
        self.project_2.setTextInteractionFlags(QtCore.Qt.TextInteractionFlag.NoTextInteraction)
        self.project_2.setObjectName("project_2")
        self.greeting_text_2 = QtWidgets.QLabel(Form)
        self.greeting_text_2.setGeometry(QtCore.QRect(30, 70, 281, 41))
        font = QtGui.QFont()
        font.setPointSize(22)
        self.greeting_text_2.setFont(font)
        self.greeting_text_2.setStyleSheet("")
        self.greeting_text_2.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.greeting_text_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.greeting_text_2.setObjectName("greeting_text_2")
        self.purpose = QtWidgets.QTextEdit(Form)
        self.purpose.setGeometry(QtCore.QRect(630, 100, 241, 71))
        self.purpose.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.CursorShape.ArrowCursor))
        self.purpose.setStyleSheet("QTextEdit {\n"
"\n"
"background-color: \"white\"\n"
"\n"
"}")
        self.purpose.setCursorWidth(1)
        self.purpose.setObjectName("purpose")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def complete_surgery(self):

        # Get Skull Leveling values
        bregma_pos = self.bregma_val
        lambda_pos = self.lambda_val
        level_left_pos = self.level_left_val
        level_right_pos = self.level_right_val

        # Get GRIN Lens positions
        grin_hemisphere = self.grin_hs_val
        grin_target = self.grin_target_val

        try:
            grin_ap = float(self.grin_ap_val)
            grin_ml = float(self.grin_ml_val)
            grin_dv = float(self.grin_dv_val)
            grin_angle = float(self.grin_angle_val)
        
        except TypeError:
            grin_ap = None
            grin_ml = None
            grin_dv = None
            grin_angle = None
        
        grin_notes = self.grin_notes

        # Get GCaMP Values
        gcamp_type = self.gcamp_type_val
        gcamp_hemisphere = self.gcamp_hs_val
        gcamp_target = self.gcamp_target_val

        try:
            gcamp_ap = float(self.gcamp_ap_val)
            gcamp_ml = float(self.gcamp_ml_val)
            gcamp_dv = float(self.gcamp_dv_val)
            gcamp_angle = float(self.gcamp_angle_val)
            gcamp_vol = float(self.gcamp_vol_val)
            gcamp_rate = float(self.gcamp_rate_val)

        except TypeError:
            gcamp_ap = None
            gcamp_ml = None
            gcamp_dv = None
            gcamp_angle = None
            gcamp_vol = None
            gcamp_rate = None

        gcamp_bevel = self.gcamp_bevel_val

        # Get Channel Rhodopsin Values

        chr_type = self.chr_type_val
        chr_hemisphere = self.chr_hs_val
        chr_target = self.chr_target_val

        try:
            chr_ap = float(self.chr_ap_val)
            chr_ml = float(self.chr_ml_val)
            chr_dv = float(self.chr_dv_val)
            chr_angle = float(self.chr_angle_val)
            chr_vol = float(self.chr_vol_val)
            chr_rate = float(self.chr_rate_val)
        
        except TypeError:
            chr_ap = None
            chr_ml = None
            chr_dv = None
            chr_angle = None
            chr_vol = None
            chr_rate = None
        
        chr_bevel = self.chr_bevel_val

        # Get Tracer Values

        tracer_type = self.tracer_type_val
        tracer_hemisphere = self.tracer_hs_val
        tracer_target = self.tracer_target_val

        try:
            tracer_ap = float(self.tracer_ap_val)
            tracer_ml = float(self.tracer_ml_val)
            tracer_dv = float(self.tracer_dv_val)
            tracer_angle = float(self.tracer_angle_val)
            tracer_vol = float(self.tracer_vol_val)
            tracer_rate = float(self.tracer_rate_val)
        
        except TypeError:
            tracer_ap = None
            tracer_ml = None
            tracer_dv = None
            tracer_angle = None
            tracer_vol = None
        
        tracer_bevel = self.tracer_bevel_val

        # Get headplate information
        num_screws = float(self.hp_screws_val)
        skull_hash = self.hp_hashing_val
        headplate_notes = self.hp_notes
        

        # Get surgeon information
        surgeon = self.surgeon_val
        stereotax = self.stereotax_val

        # Get patient information
        subject_id = self.patient_val
        subject_alias = self.alias_val
        subject_weight = self.weight_val
        subject_description = self.purpose

        # Get start and stop times
        start_time = dt_parser.parse(self.start_time)
        start_time = start_time.replace(tzinfo=tzlocal())
        end_time = dt_parser.parse(self.finish_time)
        end_time = end_time.replace(tzinfo=tzlocal())




    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Scalpel!"))
        self.save_metadata_btn.setToolTip(_translate("Form", "<html><head/><body><p>Add the surgery information to the subject\'s file!</p></body></html>"))
        self.save_metadata_btn.setText(_translate("Form", "Submit Metadata"))
        self.surgeon.setPlainText(_translate("Form", "Surgeon"))
        self.start.setPlainText(_translate("Form", "Start Time"))
        self.surgeon_val.setPlaceholderText(_translate("Form", "Your Name"))
        self.finish.setPlainText(_translate("Form", "End Time"))
        self.stereotax_val.setPlaceholderText(_translate("Form", "i.e. Alpha"))
        self.stereotax.setPlainText(_translate("Form", "Stereotax"))
        self.lambda_val.setPlaceholderText(_translate("Form", "Position"))
        self.bregma_val.setPlaceholderText(_translate("Form", "Position"))
        self.bregma.setPlainText(_translate("Form", "Bregma"))
        self.lmbda.setPlainText(_translate("Form", "Lambda"))
        self.level_right.setPlainText(_translate("Form", "Level Right"))
        self.level_right_val.setPlaceholderText(_translate("Form", "Position"))
        self.level_left.setPlainText(_translate("Form", "Level Left"))
        self.level_left_val.setPlaceholderText(_translate("Form", "Position"))
        self.patient_val.setPlaceholderText(_translate("Form", "Subject ID"))
        self.patient.setPlainText(_translate("Form", "Patient"))
        self.alias_val.setPlaceholderText(_translate("Form", "Subject Alias"))
        self.alias.setPlainText(_translate("Form", "AKA"))
        self.hp_screws_val.setPlaceholderText(_translate("Form", "Number"))
        self.hp_screws.setToolTip(_translate("Form", "How many screws did you place?"))
        self.hp_screws.setPlainText(_translate("Form", "Num Screws"))
        self.hp_label.setText(_translate("Form", "Headplate"))
        self.hp_hashing_val.setPlaceholderText(_translate("Form", "True/False"))
        self.hp_hashing.setPlainText(_translate("Form", "Skull Hash?"))
        self.grin_target.setPlainText(_translate("Form", "Target"))
        self.grin_target_val.setPlaceholderText(_translate("Form", "i.e. mPFC"))
        self.grin_hs_val.setPlaceholderText(_translate("Form", "L/R"))
        self.grin_hs.setToolTip(_translate("Form", "Which hemisphere did you place the GRIN in?"))
        self.grin_hs.setPlainText(_translate("Form", "Hemisphere"))
        self.grin_label.setText(_translate("Form", "GRIN Lens"))
        self.grin_dv_val.setPlaceholderText(_translate("Form", "Position"))
        self.grin_dv.setPlainText(_translate("Form", "DV"))
        self.grin_ml.setPlainText(_translate("Form", "ML"))
        self.grin_ml_val.setPlaceholderText(_translate("Form", "Position"))
        self.grin_ap.setPlainText(_translate("Form", "AP"))
        self.grin_ap_val.setPlaceholderText(_translate("Form", "Position"))
        self.grin_angle_val.setPlaceholderText(_translate("Form", "Empty if None"))
        self.grin_angle.setPlainText(_translate("Form", "Angle"))
        self.grin_notes.setPlaceholderText(_translate("Form", "Notes"))
        self.gcamp_target_val.setPlaceholderText(_translate("Form", "i.e. mPFC"))
        self.gcamp_val.setPlainText(_translate("Form", "DV"))
        self.gcamp_dv_val.setPlaceholderText(_translate("Form", "Position"))
        self.gcamp_hs_val.setPlaceholderText(_translate("Form", "L/R"))
        self.gcamp_hs.setPlainText(_translate("Form", "Hemisphere"))
        self.gcamp_ml_val.setPlaceholderText(_translate("Form", "Position"))
        self.gcamp_angle_val.setPlaceholderText(_translate("Form", "Empty if None"))
        self.gcamp_ap_val.setPlaceholderText(_translate("Form", "Position"))
        self.gcamp_ap.setPlainText(_translate("Form", "AP"))
        self.gcamp_notes.setPlaceholderText(_translate("Form", "Notes"))
        self.gcamp_label.setText(_translate("Form", "GCaMP"))
        self.gcamp_angle.setPlainText(_translate("Form", "Angle"))
        self.gcamp_ml.setPlainText(_translate("Form", "ML"))
        self.gcamp_target.setPlainText(_translate("Form", "Target"))
        self.chr_angle.setPlainText(_translate("Form", "Angle"))
        self.chr_ml.setPlainText(_translate("Form", "ML"))
        self.chr_label.setText(_translate("Form", "ChR"))
        self.chr_notes.setPlaceholderText(_translate("Form", "Notes"))
        self.chr_ap_val.setPlaceholderText(_translate("Form", "Position"))
        self.chr_angle_val.setPlaceholderText(_translate("Form", "Empty if None"))
        self.chr_dv_val.setPlaceholderText(_translate("Form", "Position"))
        self.chr_hs_val.setPlaceholderText(_translate("Form", "L/R"))
        self.chr_target.setPlainText(_translate("Form", "Target"))
        self.chr_ap.setPlainText(_translate("Form", "AP"))
        self.chr_dv.setPlainText(_translate("Form", "DV"))
        self.chr_ml_val.setPlaceholderText(_translate("Form", "Position"))
        self.chr_target_val.setPlaceholderText(_translate("Form", "i.e. mPFC"))
        self.chr_hs.setPlainText(_translate("Form", "Hemisphere"))
        self.tracer_angle_val.setPlaceholderText(_translate("Form", "Empty if None"))
        self.tracer_ml.setPlainText(_translate("Form", "ML"))
        self.tracer_ap_val.setPlaceholderText(_translate("Form", "Position"))
        self.tracer_ap.setPlainText(_translate("Form", "AP"))
        self.tracer_dv.setPlainText(_translate("Form", "DV"))
        self.tracer_target.setPlainText(_translate("Form", "Target"))
        self.tracer_dv_val.setPlaceholderText(_translate("Form", "Position"))
        self.tracer_ml_val.setPlaceholderText(_translate("Form", "Position"))
        self.tracer_hs_val.setPlaceholderText(_translate("Form", "L/R"))
        self.tracer_target_val.setPlaceholderText(_translate("Form", "i.e. mPFC"))
        self.tracer_label.setText(_translate("Form", "Tracer"))
        self.tracer_angle.setPlainText(_translate("Form", "Angle"))
        self.tracer_notes.setPlaceholderText(_translate("Form", "Notes"))
        self.tracer_hs.setPlainText(_translate("Form", "Hemisphere"))
        self.greeting_label.setText(_translate("Form", "Greetings, Doctor!"))
        self.leveling_label.setText(_translate("Form", "Skull Leveling"))
        self.gcamp_vol.setPlainText(_translate("Form", "Volume"))
        self.gcamp_vol_val.setPlaceholderText(_translate("Form", "nL"))
        self.gcamp_rate_val.setPlaceholderText(_translate("Form", "nl/min"))
        self.gcamp_rate.setPlainText(_translate("Form", "Vol/Min Rate"))
        self.gcamp_bevel_val.setPlaceholderText(_translate("Form", "i.e. front"))
        self.gcamp_bevel.setToolTip(_translate("Form", "Position relative to mouse (ie front is away from you)"))
        self.gcamp_bevel.setPlainText(_translate("Form", "Bevel Pos"))
        self.chr_vol_val.setPlaceholderText(_translate("Form", "nL"))
        self.chr_vol.setPlainText(_translate("Form", "Volume"))
        self.chr_rate_val.setPlaceholderText(_translate("Form", "nL/min"))
        self.chr_bevel_val.setPlaceholderText(_translate("Form", "i.e. front"))
        self.chr_rate.setPlainText(_translate("Form", "Vol/Min Rate"))
        self.chr_bevel.setPlainText(_translate("Form", "Bevel Pos"))
        self.tracer_rate.setPlainText(_translate("Form", "Vol/Min Rate"))
        self.tracer_bevel_val.setPlaceholderText(_translate("Form", "i.e. front"))
        self.tracer_vol_rate.setPlaceholderText(_translate("Form", "nL/min"))
        self.tracer_vol.setPlainText(_translate("Form", "Volume"))
        self.tracer_bevel.setPlainText(_translate("Form", "Bevel Pos"))
        self.tracer_vol_val.setPlaceholderText(_translate("Form", "nL"))
        self.hp_notes.setPlaceholderText(_translate("Form", "Notes"))
        self.death_notes.setPlaceholderText(_translate("Form", "Notes"))
        self.death_btn.setToolTip(_translate("Form", "If your animal dies during surgery, enter your notes and hit this button."))
        self.death_btn.setText(_translate("Form", "Record Death"))
        self.weight_val.setPlaceholderText(_translate("Form", "Grams"))
        self.project_2.setPlainText(_translate("Form", "Weight"))
        self.greeting_text_2.setText(_translate("Form", "Your scalpel awaits..."))
        self.purpose.setPlaceholderText(_translate("Form", "Purpose"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec())
